spring.application.name=prisha-aura-api

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/prisha_aura_db
spring.datasource.username=root
spring.datasource.password=Root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true